
package asianServerServices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AsianServerImplService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8081/Asia?wsdl")
public class AsianServerImplService
    extends Service
{

    private final static URL ASIANSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ASIANSERVERIMPLSERVICE_EXCEPTION;
    private final static QName ASIANSERVERIMPLSERVICE_QNAME = new QName("http://server/", "AsianServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/Asia?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASIANSERVERIMPLSERVICE_WSDL_LOCATION = url;
        ASIANSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public AsianServerImplService() {
        super(__getWsdlLocation(), ASIANSERVERIMPLSERVICE_QNAME);
    }

    public AsianServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASIANSERVERIMPLSERVICE_QNAME, features);
    }

    public AsianServerImplService(URL wsdlLocation) {
        super(wsdlLocation, ASIANSERVERIMPLSERVICE_QNAME);
    }

    public AsianServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASIANSERVERIMPLSERVICE_QNAME, features);
    }

    public AsianServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsianServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameServer
     */
    @WebEndpoint(name = "AsianServerImplPort")
    public GameServer getAsianServerImplPort() {
        return super.getPort(new QName("http://server/", "AsianServerImplPort"), GameServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameServer
     */
    @WebEndpoint(name = "AsianServerImplPort")
    public GameServer getAsianServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "AsianServerImplPort"), GameServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASIANSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw ASIANSERVERIMPLSERVICE_EXCEPTION;
        }
        return ASIANSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
