
package asianServerServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameServer", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameServer {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlayerStatus", targetNamespace = "http://server/", className = "Asia.GetPlayerStatus")
    @ResponseWrapper(localName = "getPlayerStatusResponse", targetNamespace = "http://server/", className = "Asia.GetPlayerStatusResponse")
    @Action(input = "http://server/GameServer/getPlayerStatusRequest", output = "http://server/GameServer/getPlayerStatusResponse")
    public String getPlayerStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferAccount", targetNamespace = "http://server/", className = "Asia.TransferAccount")
    @ResponseWrapper(localName = "transferAccountResponse", targetNamespace = "http://server/", className = "Asia.TransferAccountResponse")
    @Action(input = "http://server/GameServer/transferAccountRequest", output = "http://server/GameServer/transferAccountResponse")
    public String transferAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPlayerAccount", targetNamespace = "http://server/", className = "Asia.CreatePlayerAccount")
    @ResponseWrapper(localName = "createPlayerAccountResponse", targetNamespace = "http://server/", className = "Asia.CreatePlayerAccountResponse")
    @Action(input = "http://server/GameServer/createPlayerAccountRequest", output = "http://server/GameServer/createPlayerAccountResponse")
    public String createPlayerAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignIn", targetNamespace = "http://server/", className = "Asia.PlayerSignIn")
    @ResponseWrapper(localName = "playerSignInResponse", targetNamespace = "http://server/", className = "Asia.PlayerSignInResponse")
    @Action(input = "http://server/GameServer/playerSignInRequest", output = "http://server/GameServer/playerSignInResponse")
    public String playerSignIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignOut", targetNamespace = "http://server/", className = "Asia.PlayerSignOut")
    @ResponseWrapper(localName = "playerSignOutResponse", targetNamespace = "http://server/", className = "Asia.PlayerSignOutResponse")
    @Action(input = "http://server/GameServer/playerSignOutRequest", output = "http://server/GameServer/playerSignOutResponse")
    public String playerSignOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendAccount", targetNamespace = "http://server/", className = "Asia.SuspendAccount")
    @ResponseWrapper(localName = "suspendAccountResponse", targetNamespace = "http://server/", className = "Asia.SuspendAccountResponse")
    @Action(input = "http://server/GameServer/suspendAccountRequest", output = "http://server/GameServer/suspendAccountResponse")
    public String suspendAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
