package GameServerApp;


/**
* GameServerApp/GameServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, June 11, 2020 4:58:05 o'clock PM EDT
*/

public interface GameServer extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameServer
