package GameServerApp;

/**
* GameServerApp/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, June 11, 2020 4:58:05 o'clock PM EDT
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServerApp.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (GameServerApp.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServerApp.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServerApp.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServerApp.GameServerHelper.type ();
  }

}
