package GameServerApp;


/**
* GameServerApp/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, June 11, 2020 4:58:05 o'clock PM EDT
*/

public interface GameServerOperations 
{
  String createPlayerAccount (String FirstName, String LastName, int Age, String Username, String Password, String IPAddress);
  String playerSignIn (String Username, String Password, String IPAddress);
  String playerSignOut (String Username, String IPAddress);
  String transferAccount (String Username, String Password, String OldIPAddress, String NewIPAddress);
  String getPlayerStatus (String AdminUsername, String AdminPassword, String AdminIPAddress);
  String suspendAccount (String AdminUsername, String AdminPassword, String AdminIPAddress, String UsernameToSuspend);
  void shutdown ();
} // interface GameServerOperations
