package FrontEndApp;


/**
* FrontEndApp/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Wednesday, July 22, 2020 4:54:52 o'clock PM EDT
*/

public interface FrontEndOperations 
{
  String createPlayerAccount (String FirstName, String LastName, int Age, String Username, String Password, String IPAddress);
  String playerSignIn (String Username, String Password, String IPAddress);
  String playerSignOut (String Username, String IPAddress);
  String transferAccount (String Username, String Password, String OldIPAddress, String NewIPAddress);
  String getPlayerStatus (String AdminUsername, String AdminPassword, String AdminIPAddress);
  String suspendAccount (String AdminUsername, String AdminPassword, String AdminIPAddress, String UsernameToSuspend);
  void shutdown ();
} // interface FrontEndOperations
