
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EuropeanServerImplService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8082/Europe?wsdl")
public class EuropeanServerImplService
    extends Service
{

    private final static URL EUROPEANSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EUROPEANSERVERIMPLSERVICE_EXCEPTION;
    private final static QName EUROPEANSERVERIMPLSERVICE_QNAME = new QName("http://server/", "EuropeanServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/Europe?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EUROPEANSERVERIMPLSERVICE_WSDL_LOCATION = url;
        EUROPEANSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public EuropeanServerImplService() {
        super(__getWsdlLocation(), EUROPEANSERVERIMPLSERVICE_QNAME);
    }

    public EuropeanServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EUROPEANSERVERIMPLSERVICE_QNAME, features);
    }

    public EuropeanServerImplService(URL wsdlLocation) {
        super(wsdlLocation, EUROPEANSERVERIMPLSERVICE_QNAME);
    }

    public EuropeanServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EUROPEANSERVERIMPLSERVICE_QNAME, features);
    }

    public EuropeanServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EuropeanServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameServer
     */
    @WebEndpoint(name = "EuropeanServerImplPort")
    public GameServer getEuropeanServerImplPort() {
        return super.getPort(new QName("http://server/", "EuropeanServerImplPort"), GameServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameServer
     */
    @WebEndpoint(name = "EuropeanServerImplPort")
    public GameServer getEuropeanServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "EuropeanServerImplPort"), GameServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EUROPEANSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw EUROPEANSERVERIMPLSERVICE_EXCEPTION;
        }
        return EUROPEANSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
